language: python
python:
    - "2.7"
    - "3.7"
    - "3.7-dev"  # 3.7 development branch

  # command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install dpkg-dev build-essential freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libjpeg-dev libnotify-dev libpng-dev libsdl2-dev libsm-dev libtiff-dev libwebkit2gtk-4.0-dev libxtst-dev


install:
  - pip install -r requirements.txt
